export const COLOR ={
  LIGHT_PINK: "#FFE6EF",
  PINK: "#FB99BC",
  DARK_PINK: "#FC70A3",
  WHITE: "#FFFFFF",
  LIGHT_GRAY_1: "#F0E9EC",
  LIGHT_GRAY_2: "#E0D9DC",
  LIGHT_GRAY_3: "#C9C0C4",
  DARK_GRAY: "#ACA2A6",
};
